import { ThemePreset, ThemeEffects } from '../types/theme';

const baseTimestamp = Date.now();

const defaultEffects: ThemeEffects = {
  glowStrength: 'subtle',
  ambience: 'balanced',
  glassmorphism: true,
};

export const themePresets: ThemePreset[] = [
  {
    id: 'lunar-eclipse',
    name: 'Lunar Eclipse',
    description:
      'Deep space blacks with eclipse orange accents and glassmorphism panels. Best for night traders and immersive experience.',
    colors: {
      background: '#0A0A0F',
      backgroundSecondary: '#11121A',
      backgroundTertiary: '#181B26',
      text: '#E8EAF6',
      textSecondary: '#C5CADE',
      textMuted: '#8B92A9',
      primary: '#FF6B35',
      primaryHover: '#FF5722',
      primaryActive: '#E64A19',
      accent: '#FF8C42',
      accentHover: '#FF7A29',
      success: '#4ECDC4',
      warning: '#FFB347',
      error: '#FF6B6B',
      info: '#4A90E2',
      border: '#232838',
      borderHover: '#32394F',
      chartBullish: '#4ECDC4',
      chartBearish: '#FF6B6B',
      chartNeutral: '#818CF8',
      gradientStart: '#0A0A0F',
      gradientMiddle: '#131426',
      gradientEnd: '#1E2438',
      deepSpace: '#050812',
      eclipseOrange: '#FF6B35',
      moonlightSilver: '#E8EAF6',
      shadowAccent: '#1F2433',
    },
    effects: {
      glowStrength: 'normal',
      ambience: 'immersive',
      glassmorphism: true,
    },
  },
  {
    id: 'professional-dark',
    name: 'Professional Dark',
    description:
      'Bloomberg-inspired pure blacks with crisp typography and data-first visuals. Best for serious traders and data-first approach.',
    colors: {
      background: '#000000',
      backgroundSecondary: '#090909',
      backgroundTertiary: '#141414',
      text: '#FFFFFF',
      textSecondary: '#CCCCCC',
      textMuted: '#888888',
      primary: '#00A3FF',
      primaryHover: '#0088D1',
      primaryActive: '#006BA3',
      accent: '#FFA726',
      accentHover: '#FB8C00',
      success: '#00E676',
      warning: '#FFD740',
      error: '#FF5252',
      info: '#40C4FF',
      border: '#1F1F1F',
      borderHover: '#2E2E2E',
      chartBullish: '#00E676',
      chartBearish: '#FF5252',
      chartNeutral: '#40C4FF',
      gradientStart: '#000000',
      gradientMiddle: '#090909',
      gradientEnd: '#141414',
    },
    effects: {
      glowStrength: 'none',
      ambience: 'minimal',
      glassmorphism: false,
    },
  },
  {
    id: 'light-professional',
    name: 'Light Professional',
    description:
      'Clean whites with subtle shadows, pastel accents, and daylight-optimized readability. Best for day traders and bright environments.',
    colors: {
      background: '#FFFFFF',
      backgroundSecondary: '#F7F7F9',
      backgroundTertiary: '#ECEEF3',
      text: '#1C1E21',
      textSecondary: '#3A3D42',
      textMuted: '#6E737C',
      primary: '#0A84FF',
      primaryHover: '#0060DF',
      primaryActive: '#0047B3',
      accent: '#FF7B7B',
      accentHover: '#FF5C5C',
      success: '#34C759',
      warning: '#FFC300',
      error: '#FF3B30',
      info: '#5AC8FA',
      border: '#D0D5DD',
      borderHover: '#B0B7C3',
      chartBullish: '#34C759',
      chartBearish: '#FF3B30',
      chartNeutral: '#0A84FF',
      gradientStart: '#FFFFFF',
      gradientMiddle: '#F7F7F9',
      gradientEnd: '#E1E5ED',
    },
    effects: {
      glowStrength: 'subtle',
      ambience: 'minimal',
      glassmorphism: false,
    },
  },
  {
    id: 'arctic-blue',
    name: 'Arctic Blue',
    description:
      'Cool blues and professional gradients reminiscent of traditional finance terminals. Best for conservative traders and institutional look.',
    colors: {
      background: '#0F172A',
      backgroundSecondary: '#16213C',
      backgroundTertiary: '#1E2C4F',
      text: '#F8FAFC',
      textSecondary: '#CBD5E1',
      textMuted: '#94A3B8',
      primary: '#3B82F6',
      primaryHover: '#2563EB',
      primaryActive: '#1D4ED8',
      accent: '#06B6D4',
      accentHover: '#0E7490',
      success: '#10B981',
      warning: '#F59E0B',
      error: '#EF4444',
      info: '#60A5FA',
      border: '#233554',
      borderHover: '#314265',
      chartBullish: '#10B981',
      chartBearish: '#EF4444',
      chartNeutral: '#38BDF8',
      gradientStart: '#0F172A',
      gradientMiddle: '#1E3A5F',
      gradientEnd: '#2563EB',
    },
    effects: {
      glowStrength: 'subtle',
      ambience: 'balanced',
      glassmorphism: true,
    },
  },
  {
    id: 'emerald-wealth',
    name: 'Emerald Wealth',
    description:
      'Deep greens with gold accents conveying prosperity and long-term stability. Best for long-term investors and positive mindset.',
    colors: {
      background: '#064E3B',
      backgroundSecondary: '#075E46',
      backgroundTertiary: '#047857',
      text: '#ECFDF5',
      textSecondary: '#D1FAE5',
      textMuted: '#A7F3D0',
      primary: '#10B981',
      primaryHover: '#059669',
      primaryActive: '#047857',
      accent: '#FBBF24',
      accentHover: '#F59E0B',
      success: '#34D399',
      warning: '#FCD34D',
      error: '#F87171',
      info: '#5EEAD4',
      border: '#0F9F6E',
      borderHover: '#34D399',
      chartBullish: '#34D399',
      chartBearish: '#F87171',
      chartNeutral: '#FBBF24',
      gradientStart: '#064E3B',
      gradientMiddle: '#047857',
      gradientEnd: '#FBBF24',
    },
    effects: {
      glowStrength: 'normal',
      ambience: 'balanced',
      glassmorphism: true,
    },
  },
  {
    id: 'midnight-purple',
    name: 'Midnight Purple',
    description:
      'Tech-forward deep purples with neon cyan accents for modern traders. Best for tech-savvy traders and modern aesthetic.',
    colors: {
      background: '#2E1065',
      backgroundSecondary: '#3B1591',
      backgroundTertiary: '#4C1D95',
      text: '#F5F3FF',
      textSecondary: '#DDD6FE',
      textMuted: '#C4B5FD',
      primary: '#8B5CF6',
      primaryHover: '#7C3AED',
      primaryActive: '#6D28D9',
      accent: '#06B6D4',
      accentHover: '#0EA5E9',
      success: '#10B981',
      warning: '#F59E0B',
      error: '#EF4444',
      info: '#22D3EE',
      border: '#5B21B6',
      borderHover: '#7C3AED',
      chartBullish: '#10B981',
      chartBearish: '#EF4444',
      chartNeutral: '#06B6D4',
      gradientStart: '#2E1065',
      gradientMiddle: '#5B21B6',
      gradientEnd: '#06B6D4',
    },
    effects: {
      glowStrength: 'strong',
      ambience: 'immersive',
      glassmorphism: true,
    },
  },
  {
    id: 'monochrome-pro',
    name: 'Monochrome Pro',
    description:
      'Ultra-minimal monochrome palette with maximum data density and speed. Best for professional traders and focus mode.',
    colors: {
      background: '#000000',
      backgroundSecondary: '#0D0D0D',
      backgroundTertiary: '#1A1A1A',
      text: '#FFFFFF',
      textSecondary: '#E6E6E6',
      textMuted: '#999999',
      primary: '#FFFFFF',
      primaryHover: '#E6E6E6',
      primaryActive: '#CCCCCC',
      accent: '#FFFFFF',
      accentHover: '#E6E6E6',
      success: '#00FF00',
      warning: '#FFFFFF',
      error: '#FF0000',
      info: '#FFFFFF',
      border: '#333333',
      borderHover: '#4D4D4D',
      chartBullish: '#00FF00',
      chartBearish: '#FF0000',
      chartNeutral: '#FFFFFF',
      gradientStart: '#000000',
      gradientMiddle: '#0D0D0D',
      gradientEnd: '#1A1A1A',
    },
    effects: {
      glowStrength: 'none',
      ambience: 'minimal',
      glassmorphism: false,
    },
  },
];

export const defaultThemePreset = themePresets[0];

export const DEFAULT_THEME_ID = defaultThemePreset.id;

export const createThemeFromPreset = (presetId: string) => {
  const basePreset = themePresets.find(preset => preset.id === presetId) ?? defaultThemePreset;
  return {
    id: `theme-${presetId}`,
    name: basePreset.name,
    colors: basePreset.colors,
    effects: basePreset.effects ?? defaultEffects,
    isCustom: false,
    createdAt: baseTimestamp,
    updatedAt: baseTimestamp,
  };
};
